export let currentLang = localStorage.getItem("app_lang") || "hu";

export const translations = {
    hu: {
        docTitle: "Térkép Generátor",
        title: "Dungeon Generátor",
        brushSize: "Ecset méret:",
        exportBtn: "Exportálás DD2VTT-be",
        fileName: "dungeon_terkep",
        selectActiveTile: "Szerkesztett / Aktív csempe:",
        addTileBtn: "+ Új csempetípus hozzáadása",
        deleteTileBtn: "Típus törlése",
        tileNameLabel: "Név:",
        isFloorLabel: "Járható padló (DD2VTT LoS)",
        wallsTowardsLabel: "Falat von ezek felé:",
        noOtherTiles: "Nincs más típus",
        texNone: "Sima",
        texStone: "Kőpadló",
        texWood: "Fapadló",
        texCobble: "Kockakő",
        tileNothing: "Semmi",
        tileCorridor: "Folyosó",
        tileRoom: "Szoba",
        newTileDefaultName: "Új típus"
    },
    en: {
        docTitle: "Map Generator",
        title: "Dungeon Generator",
        brushSize: "Brush size:",
        exportBtn: "Export to DD2VTT",
        fileName: "dungeon_map",
        selectActiveTile: "Edited / Active Tile:",
        addTileBtn: "+ Add New Tile Type",
        deleteTileBtn: "Delete Type",
        tileNameLabel: "Name:",
        isFloorLabel: "Walkable Floor (DD2VTT LoS)",
        wallsTowardsLabel: "Draws walls towards:",
        noOtherTiles: "No other types",
        texNone: "Plain",
        texStone: "Stone Floor",
        texWood: "Wood Floor",
        texCobble: "Cobblestone",
        tileNothing: "Nothing",
        tileCorridor: "Corridor",
        tileRoom: "Room",
        newTileDefaultName: "New Type"
    },
    de: {
        docTitle: "Karten-Generator",
        title: "Dungeon-Generator",
        brushSize: "Pinselgröße:",
        exportBtn: "Als DD2VTT exportieren",
        fileName: "dungeon_karte",
        selectActiveTile: "Bearbeitete / Aktive Kachel:",
        addTileBtn: "+ Neue Kachel hinzufügen",
        deleteTileBtn: "Typ löschen",
        tileNameLabel: "Name:",
        isFloorLabel: "Begehbarer Boden (DD2VTT LoS)",
        wallsTowardsLabel: "Zieht Wände zu:",
        noOtherTiles: "Keine anderen Typen",
        texNone: "Einfach",
        texStone: "Steinboden",
        texWood: "Holzboden",
        texCobble: "Kopfsteinpflaster",
        tileNothing: "Nichts",
        tileCorridor: "Korridor",
        tileRoom: "Raum",
        newTileDefaultName: "Neuer Typ"
    },
    es: {
        docTitle: "Generador de Mapas",
        title: "Generador de Mazmorras",
        brushSize: "Tamaño de pincel:",
        exportBtn: "Exportar a DD2VTT",
        fileName: "mapa_mazmorra",
        selectActiveTile: "Casilla Editada / Activa:",
        addTileBtn: "+ Añadir Nuevo Tipo de Casilla",
        deleteTileBtn: "Eliminar Tipo",
        tileNameLabel: "Nombre:",
        isFloorLabel: "Suelo Transitable (DD2VTT LoS)",
        wallsTowardsLabel: "Dibuja paredes hacia:",
        noOtherTiles: "Sin otros tipos",
        texNone: "Liso",
        texStone: "Suelo de Piedra",
        texWood: "Suelo de Madera",
        texCobble: "Adoquín",
        tileNothing: "Nada",
        tileCorridor: "Pasillo",
        tileRoom: "Habitación",
        newTileDefaultName: "Nuevo Tipo"
    },
    fr: {
        docTitle: "Générateur de Cartes",
        title: "Générateur de Donjon",
        brushSize: "Taille du pinceau :",
        exportBtn: "Exporter vers DD2VTT",
        fileName: "carte_donjon",
        selectActiveTile: "Tuile Éditée / Active :",
        addTileBtn: "+ Ajouter un Type de Tuile",
        deleteTileBtn: "Supprimer le Type",
        tileNameLabel: "Nom :",
        isFloorLabel: "Sol Marchable (DD2VTT LoS)",
        wallsTowardsLabel: "Trace des murs vers :",
        noOtherTiles: "Aucun autre type",
        texNone: "Uni",
        texStone: "Sol en Pierre",
        texWood: "Plancher en Bois",
        texCobble: "Pavés",
        tileNothing: "Rien",
        tileCorridor: "Couloir",
        tileRoom: "Pièce",
        newTileDefaultName: "Nouveau Type"
    }
};

export function setLanguage(lang) {
    if (translations[lang]) {
        currentLang = lang;
        localStorage.setItem("app_lang", lang);
    }
}