export const translations = {
    hu: {
        docTitle: "Térkép generátor",
        title: "Dungeon Generátor",
        settingsToggle: "⚙️ Generáló Beállítások",
        widthLabel: "Térkép szélessége:",
        heightLabel: "Térkép magassága:",
        roomCountLabel: "Szobák száma:",
        generateBtn: "🎲 Dungeon Generálása",
        modeDraw: "🖌️ Csempézés",
        modeDoor: "🚪 Ajtó szerkesztés",
        brushSize: "Ecset méret:",
        wallStyleLabel: "Falstílus:",
        wallStyleRocky: "Barlangos",
        wallStyleSmooth: "Lekerekített",
        selectActiveTile: "Aktív csempe kiválasztása:",
        tileNameLabel: "Név:",
        deleteTileBtn: "Törlés",
        isFloorLabel: "Padló típus",
        texNone: "Nincs",
        texStone: "Kő",
        texWood: "Fa",
        texCobble: "Macskakő",
        wallsTowardsLabel: "Falak feléjük:",
        noOtherTiles: "Nincs másik csempe",
        addTileBtn: "+ Új csempe típus hozzáadása",
        mapFileLabel: "Térkép vagy háttér betöltése",
        exportBtn: "Exportálás DD2VTT-be",
        resizeBtn: "📐 Csak átméretezés"
    },
    en: {
        docTitle: "Map Generator",
        title: "Dungeon Generator",
        settingsToggle: "⚙️ Generator Settings",
        widthLabel: "Map Width:",
        heightLabel: "Map Height:",
        roomCountLabel: "Room Count:",
        generateBtn: "🎲 Generate Dungeon",
        modeDraw: "🖌️ Drawing",
        modeDoor: "🚪 Door Editing",
        brushSize: "Brush Size:",
        wallStyleLabel: "Wall Style:",
        wallStyleRocky: "Rocky",
        wallStyleSmooth: "Smooth",
        selectActiveTile: "Select Active Tile:",
        tileNameLabel: "Name:",
        deleteTileBtn: "Delete",
        isFloorLabel: "Floor Type",
        texNone: "None",
        texStone: "Stone",
        texWood: "Wood",
        texCobble: "Cobblestone",
        wallsTowardsLabel: "Walls towards them:",
        noOtherTiles: "No other tiles",
        addTileBtn: "+ Add New Tile Type",
        mapFileLabel: "Load Map or Background",
        exportBtn: "Export to DD2VTT",
        resizeBtn: "📐 Resize Only"
    },
    de: {
        docTitle: "Karten-Generator",
        title: "Dungeon Generator",
        settingsToggle: "⚙️ Generator-Einstellungen",
        widthLabel: "Kartenbreite:",
        heightLabel: "Kartenhöhe:",
        roomCountLabel: "Anzahl der Räume:",
        generateBtn: "🎲 Dungeon generieren",
        modeDraw: "🖌️ Zeichnen",
        modeDoor: "🚪 Tür-Bearbeitung",
        brushSize: "Pinselgröße:",
        wallStyleLabel: "Wandstil:",
        wallStyleRocky: "Felsig",
        wallStyleSmooth: "Glatt",
        selectActiveTile: "Aktives Kachel auswählen:",
        tileNameLabel: "Name:",
        deleteTileBtn: "Löschen",
        isFloorLabel: "Bodentyp",
        texNone: "Keine",
        texStone: "Stein",
        texWood: "Holz",
        texCobble: "Pflasterstein",
        wallsTowardsLabel: "Wände zu ihnen:",
        noOtherTiles: "Keine anderen Kacheln",
        addTileBtn: "+ Neuen Kischetyp hinzufügen",
        mapFileLabel: "Karte oder Hintergrund laden",
        exportBtn: "Nach DD2VTT exportieren",
        resizeBtn: "📐 Nur Größe ändern"
    },
    es: {
        docTitle: "Generador de Mapas",
        title: "Generador de Mazmorras",
        settingsToggle: "⚙️ Configuración del Generador",
        widthLabel: "Ancho del Mapa:",
        heightLabel: "Alto del Mapa:",
        roomCountLabel: "Número de Habitaciones:",
        generateBtn: "🎲 Generar Mazmorra",
        modeDraw: "🖌️ Dibujar",
        modeDoor: "🚪 Editar Puertas",
        brushSize: "Tamaño del Pincel:",
        wallStyleLabel: "Estilo de Pared:",
        wallStyleRocky: "Rocoso",
        wallStyleSmooth: "Suave",
        selectActiveTile: "Seleccionar Baldosa Activa:",
        tileNameLabel: "Nombre:",
        deleteTileBtn: "Eliminar",
        isFloorLabel: "Tipo de Suelo",
        texNone: "Ninguno",
        texStone: "Piedra",
        texWood: "Madera",
        texCobble: "Adoquín",
        wallsTowardsLabel: "Paredes hacia ellos:",
        noOtherTiles: "No hay otras baldosas",
        addTileBtn: "+ Añadir Nuevo Tipo de Baldosa",
        mapFileLabel: "Cargar Mapa o Fondo",
        exportBtn: "Exportar a DD2VTT",
        resizeBtn: "📐 Solo Redimensionar"
    },
    fr: {
        docTitle: "Générateur de Carte",
        title: "Générateur de Donjon",
        settingsToggle: "⚙️ Paramètres du Générateur",
        widthLabel: "Largeur de la Carte :",
        heightLabel: "Hauteur de la Carte :",
        roomCountLabel: "Nombre de Pièces :",
        generateBtn: "🎲 Générer le Donjon",
        modeDraw: "🖌️ Dessin",
        modeDoor: "🚪 Édition des Portes",
        brushSize: "Taille du Pinceau :",
        wallStyleLabel: "Style de Mur :",
        wallStyleRocky: "Rocheux",
        wallStyleSmooth: "Lisse",
        selectActiveTile: "Sélectionner la Tuile Active :",
        tileNameLabel: "Nom :",
        deleteTileBtn: "Supprimer",
        isFloorLabel: "Type de Sol",
        texNone: "Aucun",
        texStone: "Pierre",
        texWood: "Bois",
        texCobble: "Pavé",
        wallsTowardsLabel: "Murs vers eux :",
        noOtherTiles: "Pas d'autre tuile",
        addTileBtn: "+ Ajouter un Nouveau Type de Tuile",
        mapFileLabel: "Charger une Carte ou un Arrière-plan",
        exportBtn: "Exporter vers DD2VTT",
        resizeBtn: "📐 Redimensionner uniquement"
    }
};

export let currentLang = "hu";

export function setLanguage(lang) {
    if (translations[lang]) {
        currentLang = lang;
        localStorage.setItem("app_lang", lang);
    }
}